version: '3'

services:
  frontend:
    image: meinya/csc309-recipe-frontend
    restart: unless-stopped
    ports:
      - "7120:80"
    environment:
      - "TZ=America/Toronto"

  backend:
    image: meinya/csc309-recipe-backend
    restart: unless-stopped
    ports:
      - "9100:8000"
    environment:
      - "TZ=America/Toronto"
      - "PORT=8000"
      - "MONGODB_URI=mongodb://root:SyX2A54rb6kw@mongo:27017/RecipeAPI?authSource=admin"
      - "ALLOWED_ORIGINS=http://localhost:3000,https://recipe.muddy.ca"
      - "BASE_URL=https://express.csc309.muddy.ca"

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SyX2A54rb6kw

volumes:
  mongo: